# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock.xci
# IP: The module: 'note_decoder_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'note_decoder_clock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'note_decoder_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'note_decoder_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock.xci
# IP: The module: 'note_decoder_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'note_decoder_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'note_decoder_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/note_decoder_clock/note_decoder_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'note_decoder_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
