# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/kristbp2/cs296-33fa18-secret/music_box.cache/wt [current_project]
set_property parent.project_path /home/kristbp2/cs296-33fa18-secret/music_box.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/sine_waveform_offsets.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/sine_waveform_lengths.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/sine_waveform.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/triangle_waveform.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/square_waveform.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/saw_waveform.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/waveform_lengths.coe
add_files /home/kristbp2/cs296-33fa18-secret/wave_data_gen/waveform_offsets.coe
add_files /home/kristbp2/cs296-33fa18-secret/midi-converison/song1.coe
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/sine_wave_mem_synth_1/sine_wave_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/sine_wave_mem_synth_1/sine_wave_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/triangle_wave_mem_synth_1/triangle_wave_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/triangle_wave_mem_synth_1/triangle_wave_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/square_wave_mem_synth_1/square_wave_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/square_wave_mem_synth_1/square_wave_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/saw_wave_mem_synth_1/saw_wave_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/saw_wave_mem_synth_1/saw_wave_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/length_mem_synth_1/length_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/length_mem_synth_1/length_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/offset_mem_synth_1/offset_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/offset_mem_synth_1/offset_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/main_mem_synth_1/main_mem.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/main_mem_synth_1/main_mem.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/note_decoder_clock_synth_1/note_decoder_clock.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/note_decoder_clock_synth_1/note_decoder_clock.dcp]
add_files -quiet /home/kristbp2/cs296-33fa18-secret/music_box.runs/player_clock_synth_1/player_clock.dcp
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/music_box.runs/player_clock_synth_1/player_clock.dcp]
read_verilog -library xil_defaultlib {
  /home/kristbp2/cs296-33fa18-secret/src/modules.v
  /home/kristbp2/cs296-33fa18-secret/src/register.v
  /home/kristbp2/cs296-33fa18-secret/src/wave_counter.v
  /home/kristbp2/cs296-33fa18-secret/src/octave_decoder.v
  /home/kristbp2/cs296-33fa18-secret/src/clock_divider.v
  /home/kristbp2/cs296-33fa18-secret/src/mux_control.v
  /home/kristbp2/cs296-33fa18-secret/src/note_decoder_full.v
  /home/kristbp2/cs296-33fa18-secret/src/main.v
  /home/kristbp2/cs296-33fa18-secret/src/toplevel.v
}
read_xdc /home/kristbp2/cs296-33fa18-secret/src/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/kristbp2/cs296-33fa18-secret/src/Basys3_Master.xdc]

synth_design -top toplevel -part xc7a35tcpg236-1
write_checkpoint -noxdef toplevel.dcp
catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
