# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/length_mem/length_mem.xci
# IP: The module: 'length_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/length_mem/length_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'length_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/length_mem/length_mem.xci
# IP: The module: 'length_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kristbp2/cs296-33fa18-secret/music_box.srcs/sources_1/ip/length_mem/length_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'length_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
